### ISSUE TITLE
咨询下, 有的查询用了行锁 有的场景用rocksdb的snapshot 请问2者有什么差异呢 怎么做的考量呢

### ISSUE THREAD

**Issue by guoxiangCN** [Qihoo360/blackwidow#15]
rt

**Comment by kernelai** [comment]
能具体举例哪两条命令吗？

**Comment by guoxiangCN** [comment]
> 能具体举例哪两条命令吗？

不好意思 搞错了 blackwidow里纯查询语义的命令时没加行锁的  刚才是看到hget发现用了snapshot hget的应该主要需要get一次metakey和一次datakey 因此用了snapshot防止查询到之间并行插入的新数据， 打扰了~
