### ISSUE TITLE
关于list数据结构的疑问

### ISSUE THREAD

**Issue by lee87902407** [Qihoo360/blackwidow#2]
我在读文档的时候,产生了些疑问:
在ist结构里面,data_key由四个部分构成: 4Bytes的Key size+ key的内容 + 4Bytes的Version + 8Bytes的Index,最后的8位index是在list里面的索引,请问这个索引是类似数组的位置0,1,2,3这样的吗,如果是这样的话,那么在使用linsert从中间插入的话,会不会导致后面的元素要重新修改index的大小,导致插入性能底下

**Comment by Axlgrep** [comment]
是的，不同节点之间的索引是连续的，在中间插入可能需要重新修改前面所有节点或者后面所有节点的索引信息， 这里我们也做了一系列优化，尽量提升性能， 但是list这种数据结构据我了解，lpush, rpush等用得比较多， 从中间插入节点的场景较少

**Comment by Leviathan1995** [comment]
@lee87902407 会
